name: tmate

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - '.config'
      - '.github/workflows/tmate.yml'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
   types: started

jobs:
  build:
    runs-on: macos-11.0

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: SSH connection to Actions
      uses: csexton/debugger-action@master
